"""add location to trip

Revision ID: 667522aaa3ff
Revises: 76cd05aa2831
Create Date: 2021-07-10 13:11:48.519611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667522aaa3ff'
down_revision = '76cd05aa2831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trips', sa.Column('start_latitude', sa.Numeric(), nullable=True))
    op.add_column('Trips', sa.Column('start_longitude', sa.Numeric(), nullable=True))
    op.add_column('Trips', sa.Column('finish_latitude', sa.Numeric(), nullable=True))
    op.add_column('Trips', sa.Column('finish_longitude', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Trips', 'finish_longitude')
    op.drop_column('Trips', 'finish_latitude')
    op.drop_column('Trips', 'start_longitude')
    op.drop_column('Trips', 'start_latitude')
    # ### end Alembic commands ###
