"""gmail user

Revision ID: 76cd05aa2831
Revises: 315d418193c0
Create Date: 2021-07-03 13:37:27.570657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cd05aa2831'
down_revision = '315d418193c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('gmail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'gmail')
    # ### end Alembic commands ###
