"""addtrips table

Revision ID: 95978d7f0ea0
Revises: 7a50a7dc2fc8
Create Date: 2021-05-29 11:36:05.535251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95978d7f0ea0'
down_revision = '7a50a7dc2fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trips')
    # ### end Alembic commands ###
