"""initial

Revision ID: b873275f7802
Revises: 
Create Date: 2021-07-18 22:59:33.980946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b873275f7802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('gmail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_latitude', sa.Numeric(), nullable=True),
    sa.Column('start_longitude', sa.Numeric(), nullable=True),
    sa.Column('finish_latitude', sa.Numeric(), nullable=True),
    sa.Column('finish_longitude', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trips')
    op.drop_table('Users')
    # ### end Alembic commands ###
