"""report

Revision ID: ebe080c7079c
Revises: 667522aaa3ff
Create Date: 2021-07-12 16:10:34.864624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe080c7079c'
down_revision = '667522aaa3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trips', sa.Column('report', sa.Text(), nullable=True))
    op.drop_column('Trips', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trips', sa.Column('comment', sa.TEXT(), nullable=True))
    op.drop_column('Trips', 'report')
    # ### end Alembic commands ###
